### ISSUE TITLE
Color setting not applied to corners or text

### ISSUE THREAD

**Issue by bgins** [andre-dietrich/elm-svgbob#1]
Thank you for this library! I have started playing with it, and I can see that I will have many uses for it.

I noticed that when I use custom settings, the color is not applied to corners or text. Here is an Ellie that demonstrates it: https://ellie-app.com/bByhfKrxq43a1

Is there a way to apply color to these?

**Comment by andre-dietrich** [comment]
Hi and thanks for the error report,

just updated to version 2.1.1 that fixes the color settings, colors are now strings and you can define a textColor in the settings... the empty circles need to fixed ... 

Regrads

**Comment by andre-dietrich** [comment]
fix for bgColor in circle .... https://ellie-app.com/bPczw95LxqHa1

**Comment by bgins** [comment]
Awesome, works great. Thanks for the fixes!
